### ISSUE TITLE
No Active Cases

### ISSUE THREAD

**Issue by natyavidhan** [M-Media-Group/Covid-19-API#22]
I know that what you have provided is already too much but if it is possible then it would be really great to add active cases

thank you!
:D

**Comment by mwargan** [comment]
Hey @studiousgamer - active cases is a tad more complex. It turns out that some (most?) countries have stopped following up with people sick at-home with COVID, and so they don't report when they are no longer sick. Because of this, it's hard to give an accurate active cases count.

You have some alternatives though, like you can fetch the cases today, and the cases yesterday (using the history endpoint), and calculate the new cases in any given day. It's not exactly active cases, but usually covers most use-cases.

**Comment by natyavidhan** [comment]
okay sure!
