### ISSUE TITLE
Daily data

### ISSUE THREAD

**Issue by leandroparedes** [M-Media-Group/Covid-19-API#8]
Include today's confirmed and today's deaths count in the cases data.

I've implemented this on the wrapper I'm using but it would be great having this natively.

[Link to the wrapper](https://github.com/leandroparedes/covid-api-wrapper)

**Comment by mwargan** [comment]
@leandroparedes what do you mean specifically? In https://covid-api.mmediagroup.fr/v1/cases you have confirmed, deaths, and recovered (which will be deprecated soon from the cases endpoint).

Or do you mean to show only todays cases less yesterdays cases?

**Comment by leandroparedes** [comment]
I mean the difference between today and yesterday. How many new cases and deaths are.

**Comment by mwargan** [comment]
Got it! Currently the way you are doing it is the way we expect it to be done, via two API calls.

This is mostly because we can not always guarantee that there is data from yesterday. In some timezones the day would have already changed to a new one but the data wouldn't have caught up, effectively having a couple hour period everyday where the previous day results aren't available.

This is due to the data-source, so not much can be done on the API side.
