### ISSUE TITLE
Missing updated field

### ISSUE THREAD

**Issue by leandroparedes** [M-Media-Group/Covid-19-API#9]
Some countries doesn't have the `updated` field on the `/cases` endpoint. This are the ones I have noticed:
- US
- China

**Comment by mwargan** [comment]
@leandroparedes great catch! These countries don't have an updated field because there isn't an actual metric for the "All" region for them, it's summed up from all the subregions. Because the subregions are updated at different times, it is impossible to determine when the total data is actually from.

I might be able to just put the most recently updated timestamp in All but I think that won't be accurate.

**Comment by leandroparedes** [comment]
I guess that makes sense.
